In [2]:
# this is a document for practicing xarray
import xarray as xr 
import numpy as np
import pandas as pd

In [3]:
data = xr.DataArray(np.random.randn(2, 3), dims=("x", "y"), coords={"x": [10, 20]})
print(data)

<xarray.DataArray (x: 2, y: 3)> Size: 48B
array([[-0.59312836, -0.33274616, -0.60990462],
       [ 0.30025129,  0.10275312,  0.98056383]])
Coordinates:
  * x        (x) int64 16B 10 20
Dimensions without coordinates: y


In [10]:
# trying to create the strcture of the output I need
data = xr.DataArray(np.random.randn(3, 2), dims=("models", "ouptus"), coords={"models": ["growth_rate", "frequency","fluxes"], "ouptus": ["value", "error"]})
print(data)
print(data.sel(models="growth_rate").sel(ouptus="error"))

<xarray.DataArray (models: 3, ouptus: 2)> Size: 48B
array([[ 0.16279636, -1.68150281],
       [ 0.35403153,  0.55044644],
       [-1.13053564,  1.82362822]])
Coordinates:
  * models   (models) <U11 132B 'growth_rate' 'frequency' 'fluxes'
  * ouptus   (ouptus) <U5 40B 'value' 'error'
<xarray.DataArray ()> Size: 8B
array(-1.68150281)
Coordinates:
    models   <U11 44B 'growth_rate'
    ouptus   <U5 20B 'error'


In [ ]:
# add a new model, thank you chat gpt:
new_model = xr.DataArray(
    np.array([[1.23, 0.05]]),  # shape (1, 2)
    dims=("models", "outputs"),
    coords={
        "models": ["temperature"],
        "outputs": ["value", "error"]
    }
)

# Concatenate along the 'models' dimension
data = xr.concat([data, new_model], dim="models")
print(data)


<xarray.DataArray (models: 4, ouptus: 2, outputs: 2)> Size: 128B
array([[[ 0.16279636,  0.16279636],
        [-1.68150281, -1.68150281]],

       [[ 0.35403153,  0.35403153],
        [ 0.55044644,  0.55044644]],

       [[-1.13053564, -1.13053564],
        [ 1.82362822,  1.82362822]],

       [[ 1.23      ,  0.05      ],
        [ 1.23      ,  0.05      ]]])
Coordinates:
  * models   (models) <U11 176B 'growth_rate' 'frequency' 'fluxes' 'temperature'
  * ouptus   (ouptus) <U5 40B 'value' 'error'
  * outputs  (outputs) <U5 40B 'value' 'error'
